---
engines:
  duplication:
    exclude_paths:
      - "src/docGeneratorMain.ts"
    config:
      languages:
        - "typescript"
  complexity:
    exclude_paths:
      - "src/docGeneratorMain.ts"
    config:
      languages:
        - "typescript"
